name = "mancala_game"
description = "The classic Mancala game written in Ada."
version = "0.1.0-dev"

authors = ["Stefan Papin"]
maintainers = ["Stefan Papin <stefan@papinologies.com>"]
maintainers-logins = ["pastpap"]
licenses = "Apache-2.0 WITH LLVM-exception"
website = "papinologies.com"
tags = []

executables = ["main"]

[[depends-on]]
aunit = "^25.0.0"

[[depends-on]]
aws = "^24.0.0"
